# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, "10.3"
use_frameworks!

target 'MyBlog' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for MyBlog
  pod 'SwiftyJSON'

  # target 'MyBlog' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # target 'MyBlog' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
